### ISSUE TITLE
Why is this repository claiming copyright for CurrikiStudio?

### ISSUE THREAD

**Issue by otacke** [ActiveLearningStudio/H5P.Essay-1.2#1]
@basit-tkxel @ActiveLearningStudio

Hi! This is kind of a follow up to https://github.com/h5p/h5p-simple-multiple-choice/pull/57 where I suddenly did not get an answer anymore.

I just wanted to let you know that I am still the maintainer and copyright owner of H5P.Essay (see https://github.com/otacke/h5p-essay) that you are using an old version of here. Even though I don't mind others re-using and re-purposing the code - that's why I used the MIT license, I want to express my disappointment and disapproval of the audacity to not change one single line of code but naming CurrikiStudio the sole copyright owner and not even referencing me: https://github.com/ActiveLearningStudio/H5P.Essay-1.2/blob/6ec9635af7a55773b24b172d5ec0c980d7048f96/LICENSE#L3 That's not the spirit of open and libre software.

Same issue is true for all the other code that was copied from the H5P repositories and now lists CurrikiStudio as the sole copyright owner, not mentioning Joubel AS / H5P Group / H5P.

**Comment by CurrikiMike** [comment]
otacke - We love your essay and are big fans of all of the H5P work. We have been cleaning up our repos and we incorrectly attributed Curriki when adding the license files. We are fixing this now to provide the correct licenses and attributions to every repository we forked. We will let you know as soon as these corrections are made. Thanks for bringing this to our attention.

**Comment by otacke** [comment]
@CurrikiMike No worries, no hard feelings. I was just confused by the [determination that I met when wondering about whether this change was intended or not](https://github.com/h5p/h5p-simple-multiple-choice/pull/57).
